spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/workforce
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
server.port=8080
management.endpoints.web.exposure.include=*


# SMTP Server configuration
spring.mail.protocol=smtp
spring.mail.host=smtp.live.com
spring.mail.port=587
spring.mail.username=springworkforceproject@hotmail.com
spring.mail.password=hossein6819@@



# TLS configuration
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email configuration
app.mail.sender=springactiveworkforce@gmail.com
app.mail.subject=Verification Email
app.mail.content=Please click the link below to verify your email address:



